ALTER TABLE users ADD COLUMN ext_id VARCHAR(16) UNIQUE;
ALTER TABLE farms ADD COLUMN ext_id VARCHAR(16) UNIQUE;
ALTER TABLE contact ADD COLUMN ext_id VARCHAR(16) UNIQUE;
ALTER TABLE opening_hours ADD COLUMN ext_id VARCHAR(16) UNIQUE;
